In [60]:
import numpy as np

test_prob_machine_np = np.load('./discrimination/results/mega/31machine//test-probs.npy')
print(test_prob_machine_np.shape)
test_prob_human_np = np.load('./discrimination/results/mega/test-probs.npy')
print(test_prob_human_np.shape)

(3784, 2)
(11945, 2)


In [61]:
test_prob_machine_np[:5]

array([[0.95559895, 0.04440108],
       [0.35087016, 0.64912987],
       [0.00163914, 0.9983608 ],
       [0.20768635, 0.79231364],
       [0.9966298 , 0.00337021]], dtype=float32)

In [62]:
test_pred_machine_np = test_prob_machine_np.argmax(axis=1)
test_pred_human_np = test_prob_human_np.argmax(axis=1)
test_pred_machine_np

array([0, 1, 1, ..., 0, 1, 1])

In [63]:
test_pred_human_np

array([1, 1, 1, ..., 1, 1, 0])

In [66]:
test_pred_all_np = np.concatenate((test_pred_machine_np, test_pred_human_np))
test_pred_all_np.shape

(15729,)

In [67]:
# evaluation
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import cohen_kappa_score

def evaluation(y_true, y_pred):
    acc = classification_report(y_true, y_pred, output_dict=True)['accuracy']
    s = classification_report(y_true, y_pred, output_dict=True)['weighted avg']
    precision = s['precision']
    recall = s['recall']
    f1_score = s['f1-score']
    return acc,precision,recall,f1_score


In [68]:
machine_labels = np.zeros(len(test_pred_machine_np))
evaluation(machine_labels, test_pred_machine_np)

/home/ProfYang/miniconda3/envs/grover/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(0.6284355179704016, 1.0, 0.6284355179704016, 0.771827328789354)

In [69]:
human_labels = np.ones(len(test_pred_human_np))
evaluation(human_labels, test_pred_human_np)

(0.8199246546672248, 1.0, 0.8199246546672248, 0.901053406320438)

In [71]:
all_labels = np.concatenate((machine_labels, human_labels))
evaluation(all_labels, test_pred_all_np)

(0.7738572064339755, 0.79040661558916, 0.7738572064339755, 0.7803509297606491)